ARG tag=testing
FROM sphinx:$tag
ENV LANG C.UTF-8

RUN apt-get update \
 && apt-get upgrade -y \
 && DEBIAN_FRONTEND=noninteractive TZ=UTC apt-get install -y time \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
